# Generated by Django 3.0.8 on 2020-07-16 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_auto_20200716_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangmangame',
            name='current_guess_number',
        ),
        migrations.AddField(
            model_name='hangmangame',
            name='wrong_moves',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
