# Generated by Django 3.0.8 on 2020-07-16 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_auto_20200716_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='wrong_moves',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
